version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
  win: circleci/windows@2.2.0
jobs:
  build_deb:
    description: "Build Debian packages"
    docker:
    - image: circleci/python
    steps:
    - checkout
    - run:
        name: Install debian dependencies
        command: |
          sudo apt -y update
          sudo apt -y install libldap2-dev
          sudo apt -y install fakeroot dh-lua
    - run:
        name: "Build"
        command: |
          rm debian/lua5.4.dh-lua.conf
          make deb
  build_win:
    description: "Build rock on Windows"
    executor: win/default
    steps:
    - checkout
    - run:
        name: Install hererocks
        command: |
          pip install hererocks
          hererocks bed --lua latest --no-readline --luarocks latest --verbose
          hererocks bed --show
    - run:
        name: "Build (with install)"
        command: |
          bed/bin/activate.ps1
          luarocks make rockspec/lualdap-dev-2.rockspec
    - run:
        name: "Smoke"
        command: |
          bed/bin/activate.ps1
          lua -v
          lua tests/smoke.lua
workflows:
  version: 2
  build_deb:
    jobs:
    - build_deb:
        name: "deb"
  build_win:
    jobs:
    - build_win:
        name: "windows"
