version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
jobs:
  build_and_test:
    description: "Build and test for a specific Lua version"
    parameters:
      lua:
        type: string
      compat:
        type: string
    docker:
    - image: circleci/python
    - image: docker.io/openshift/openldap-2441-centos7@sha256:b5619d4de8efec7973dbd280eb2cc462ebeb8ae6e457acef4b743b7374dd600d
    steps:
    - checkout
    - run:
        name: Install debian dependencies
        command: |
          sudo apt -y update
          sudo apt -y install libldap2-dev
          sudo apt -y install ldap-utils netcat
    - run:
        name: Install hererocks
        command: |
          pip3 install hererocks
          hererocks bed --<<parameters.lua>> --compat <<parameters.compat>> --no-readline --luarocks latest --verbose
          hererocks bed --show
    - run:
        name: Install rocks dependencies
        command: |
          source bed/bin/activate
          luarocks install busted
          luarocks install cluacov
          luarocks list
    - run:
        name: "Build"
        command: |
          source bed/bin/activate
          luarocks make rockspecs/rockspec COVERAGE=1 JUNITXML=1
    - run:
        name: "Smoke"
        command: |
          source bed/bin/activate
          lua -v
          lua -e "print(require[[lualdap]]._DESCRIPTION)"
    - run:
        name: "Wait for OpenLDAP to spin up"
        command: while ! nc -z localhost 389 ; do sleep 1 ; done
    - run:
        name: Prime and test LDAP DB
        command: ./tests/setup.sh
    - run:
        name: "Test"
        command: |
          source bed/bin/activate
          make COVERAGE=1 JUNITXML=1 check
    - codecov/upload:
        file: "*.gcov"
        flags: default
        upload_name: <<parameters.lua>>
    - store_test_results:
        path: test-reports/
workflows:
  version: 2
  build_and_test:
    jobs:
    - build_and_test:
        name: lua5.1
        lua: "lua 5.1"
        compat: default
    - build_and_test:
        name: lua5.2
        lua: "lua 5.2"
        compat: default
    - build_and_test:
        name: lua5.3
        lua: "lua 5.3"
        compat: default
    - build_and_test:
        name: lua5.4
        lua: "lua 5.4"
        compat: default
    - build_and_test:
        name: luajit2.0
        lua: "luajit 2.0"
        compat: all
    - build_and_test:
        name: luajit2.1
        lua: "luajit 2.1"
        compat: all
