version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
jobs:
  build_and_test:
    description: "Build and test for a specific Lua version"
    parameters:
      version:
        type: string
    working_directory: /lualdap
    docker:
    - image: quay.io/devurandom/lua-dev:debian10.7-1@sha256:74f50fb4818f8e9856d8f9fdc927a072425ad2d635db509422c66bfc5a8d784f
    - image: docker.io/openshift/openldap-2441-centos7@sha256:b5619d4de8efec7973dbd280eb2cc462ebeb8ae6e457acef4b743b7374dd600d
    steps:
    - checkout
    - run:
        name: Install build / test dependencies
        command: |
          apt -y update
          apt -y install libldap2-dev ldap-utils netcat
    - run:
        name: "Wait for OpenLDAP to spin up"
        command: while ! nc -z localhost 389 ; do sleep 1 ; done
    - run:
        name: Prime and test LDAP DB
        command: ./tests/setup.sh
    - run:
        name: "Build"
        environment:
        - LUAENV_VERSION: <<parameters.version>>
        command: eval "$(luaenv init -)" && luarocks make COVERAGE=1 JUNITXML=1
    - run:
        name: "Test"
        environment:
        - LUAENV_VERSION: <<parameters.version>>
        command: eval "$(luaenv init -)" && make BUILD_VARIANT=$LUAENV_VERSION COVERAGE=1 JUNITXML=1 check
    - codecov/upload:
        file: "*.gcov"
        flags: default
        upload_name: <<parameters.version>>
    - store_test_results:
        path: test-reports/
workflows:
  version: 2
  build_and_test:
    jobs:
    - build_and_test:
        name: lua-5.1.5
        version: 5.1.5
    - build_and_test:
        name: lua-5.2.4
        version: 5.2.4
    - build_and_test:
        name: lua-5.3.5
        version: 5.3.5
    - build_and_test:
        name: luajit-2.0.5
        version: luajit-2.0.5
    - build_and_test:
        name: luajit-2.1.0-beta3
        version: luajit-2.1.0-beta3
