version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
  win: circleci/windows@2.2.0
jobs:
  test_with_coverage:
    description: "Test with coverage for a specific Lua version"
    parameters:
      lua:
        type: string
    docker:
    - image: circleci/python
    steps:
    - checkout
    - run:
        name: Install debian dependencies
        command: |
          sudo apt -y update
          sudo apt -y install libldap2-dev
          sudo apt -y install ldap-utils netcat
          sudo apt -y install slapd
          sudo apt -y install apparmor-utils
          sudo aa-disable slapd
    - run:
        name: Install hererocks
        command: |
          pip3 install hererocks
          hererocks bed --<<parameters.lua>> --no-readline --luarocks latest --verbose
          hererocks bed --show
    - run:
        name: Install rocks dependencies
        command: |
          source bed/bin/activate
          luarocks install busted
          luarocks install cluacov
          luarocks install luacheck
          luarocks list
    - run:
        name: "Build (without install)"
        command: |
          source bed/bin/activate
          make LUA_INCDIR=bed/include COVERAGE=1 src/lualdap.so
    - run:
        name: "Luacheck"
        command: |
          source bed/bin/activate
          make luacheck
    - run:
        name: Prime and test LDAP DB
        command: ./tests/slapd/setup.sh
    - run:
        name: "Wait for OpenLDAP to spin up"
        command: while ! nc -z localhost 3899 ; do sleep 1 ; done
    - run:
        name: "Test with coverage"
        command: |
          source bed/bin/activate
          export LUA_CPATH="./src/?.so"
          make COVERAGE=1 JUNITXML=1 check
    - codecov/upload:
        file: "*.gcov"
        flags: default
        upload_name: <<parameters.lua>>
    - store_test_results:
        path: test-reports/
workflows:
  version: 2
  test_with_coverage:
    jobs:
    - test_with_coverage:
        name: "coverage <<matrix.lua>>"
        matrix:
           parameters:
            lua: ["lua 5.3"]
